blank_issues_enabled: false
contact_links:
  - name: Mods that are currently supported in BetterCrewLink
    url: https://github.com/OhMyGuus/BetterCrewLink-Hats#supported-hatsskins-from-mods
    about: This is to prevent spam of the same issues and suggestions that are already supported with BetterCrewLink
